[package]
name = "pin-project"
version = "0.4.28"
edition = "2018"
rust-version = "1.34"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/pin-project"
keywords = ["pin", "macros", "attribute"]
categories = ["no-std", "rust-patterns"]
exclude = ["/.*", "/ci", "/tools"]
description = """
A crate for safe and ergonomic pin-projection.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = [
    "pin-project-internal",
    "tests/ui/auxiliary",
    "tests/doc",
    "tests/expand",
    "tests/no-core",
    "tests/no-std",
    "tests/rust-2015",
]

[dependencies]
pin-project-internal = { version = "=0.4.28", path = "pin-project-internal", default-features = false }

[dev-dependencies]
pin-project-auxiliary-macro = { path = "tests/ui/auxiliary" }
rustversion = "1.0"
trybuild = "1.0"
